server {
    root /var/www/ntt/public;
    index index.php;
    server_name backend.newsthetruth.com 117.252.16.132 newsthetruth.com www.newsthetruth.com;
    include /etc/nginx/mime.types;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/run/php-fpm/www.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/backend.newsthetruth.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/backend.newsthetruth.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;
    server_name backend.newsthetruth.com 117.252.16.132 newsthetruth.com www.newsthetruth.com;

    if ($host = backend.newsthetruth.com) {
        return 301 https://$host$request_uri;
    }

    root /var/www/ntt/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php-fpm/www.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
